language: android


jdk: oraclejdk7
components:
  - build-tools-21.1.1
  - android-21
  # Additional components
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-21

before_install:
   - chmod +x gradlew