language: android

jdk: oraclejdk7

components:
   - build-tools-21.1.2
   - android-21
   - extra-android-support
   - extra-google-m2repository
   - extra-android-m2repository

before_install:
   - echo yes | android update sdk --no-ui -f